//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSMS.Host.FileServerConnectionManager.Config.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Where is the Hostplus directory?   Note: This directory must be on a local drive " +
            "that contain a file named SYEUMREQ.DBF")]
        public string Get_Host_Dialog_Description {
            get {
                return ((string)(this["Get_Host_Dialog_Description"]));
            }
            set {
                this["Get_Host_Dialog_Description"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This directory does not contain a file named {0}.  Please select another director" +
            "y.")]
        public string Invalid_Directory {
            get {
                return ((string)(this["Invalid_Directory"]));
            }
            set {
                this["Invalid_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sms|Host FileServerConnectionManager installation")]
        public string MessageBox_Title {
            get {
                return ((string)(this["MessageBox_Title"]));
            }
            set {
                this["MessageBox_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid disk specification.")]
        public string Invalid_Drive {
            get {
                return ((string)(this["Invalid_Drive"]));
            }
            set {
                this["Invalid_Drive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("The directory must be on a {0} disk drive.")]
        public string Wrong_DriveType {
            get {
                return ((string)(this["Wrong_DriveType"]));
            }
            set {
                this["Wrong_DriveType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionString is not a valid connection string.")]
        public string InvalidConnectionString {
            get {
                return ((string)(this["InvalidConnectionString"]));
            }
            set {
                this["InvalidConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionString cannot be empty")]
        public string ConnectionStringCannotBeEmpty {
            get {
                return ((string)(this["ConnectionStringCannotBeEmpty"]));
            }
            set {
                this["ConnectionStringCannotBeEmpty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionString is missing a required property - {0}")]
        public string ConnectionStringMissingRequiredProperty {
            get {
                return ((string)(this["ConnectionStringMissingRequiredProperty"]));
            }
            set {
                this["ConnectionStringMissingRequiredProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ConnectionString Data Source does not exist")]
        public string ConnectionStringDataSourceDoesNotExist {
            get {
                return ((string)(this["ConnectionStringDataSourceDoesNotExist"]));
            }
            set {
                this["ConnectionStringDataSourceDoesNotExist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source")]
        public string DataSource {
            get {
                return ((string)(this["DataSource"]));
            }
            set {
                this["DataSource"] = value;
            }
        }
    }
}
